/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imobiliaria.gui;

import imobiliaria.dao.ImoveisHibernateDao;
import imobiliaria.dao.ImoveisJdbcDao;
import imobiliaria.controle.ImoveisControle;
import imobiliaria.modelo.Imoveis;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Helfs
 */
public class CadastroImoveis extends javax.swing.JFrame {
    
    private ImoveisControle ImovelControle;
   
    private int idDoImovelCarregado;
    
    /**
     * Creates new form CadastroImoveis
     */

    public CadastroImoveis() {
        initComponents();
        this.setLocationRelativeTo(null);
        Imoveis2Table model = new Imoveis2Table();
        jTableImoveis.setModel(model);
       //por convenção iniciar pelo JDBC
        ImovelControle = new ImoveisJdbcDao();
        ArrayList<Imoveis> listaImoveis = ImovelControle.listar();
        model.setImoveis(listaImoveis);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jtfPais = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfTel = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfValorMin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfValorMax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jcbHibernate = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableImoveis = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAcoes = new javax.swing.JMenu();
        jmSalvar = new javax.swing.JMenuItem();
        jmExcluir = new javax.swing.JMenuItem();
        jmCancelar = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Imóveis");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Número:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Estado:");

        jLabel6.setText("País:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Nome do Proprietário:");

        jLabel9.setText("Telefone para Contato:");

        jtfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyReleased(evt);
            }
        });

        jtfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNumeroKeyReleased(evt);
            }
        });

        jtfBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBairroKeyReleased(evt);
            }
        });

        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyReleased(evt);
            }
        });

        jtfEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEstadoKeyReleased(evt);
            }
        });

        jtfPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPaisKeyReleased(evt);
            }
        });

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
        });

        try {
            jtfTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTelKeyReleased(evt);
            }
        });

        jLabel10.setText("Valor:");

        jtfValorMin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfValorMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValorMinKeyReleased(evt);
            }
        });

        jLabel11.setText("a");

        jtfValorMax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfValorMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValorMaxKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("R$");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("R$");

        jLabel14.setText("(ex.: 2000 refere-se a R$2000,00 - dois mil reais)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText(",00");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText(",00");

        jcbHibernate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbHibernate.setText("Hibernate");
        jcbHibernate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHibernateActionPerformed(evt);
            }
        });

        jTableImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableImoveisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableImoveis);

        jmAcoes.setText("Ações");

        jmSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmSalvar.setText("Salvar");
        jmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalvarActionPerformed(evt);
            }
        });
        jmAcoes.add(jmSalvar);

        jmExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmExcluir.setText("Excluir");
        jmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExcluirActionPerformed(evt);
            }
        });
        jmAcoes.add(jmExcluir);

        jmCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmCancelar.setText("Cancelar");
        jmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCancelarActionPerformed(evt);
            }
        });
        jmAcoes.add(jmCancelar);

        jmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmAcoes.add(jmSair);

        jMenuBar1.add(jmAcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfPais))
                                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNome)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfValorMin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel14)))))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jcbHibernate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfValorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtfValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jcbHibernate)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalvarActionPerformed
       if(!validaSeVazio()){
       JOptionPane.showMessageDialog(this, "Campos com valores nulos ou invalidos!!!", 
       "ERRO", JOptionPane.ERROR_MESSAGE);
       return;
       }
     
       Imoveis imovel = new Imoveis();
       if (idDoImovelCarregado != 0) 
            imovel.setCodigo(idDoImovelCarregado);
            //idDoImovelCarregado = 0;
            imovel.setEndereco(jtfEndereco.getText());
            imovel.setNumero(jtfNumero.getText());
            imovel.setBairro(jtfBairro.getText());
            imovel.setCidade(jtfCidade.getText());
            imovel.setEstado(jtfEstado.getText());
            imovel.setPais(jtfPais.getText());
            imovel.setProprietario(jtfNome.getText());
            imovel.setTelefone(jtfTel.getText());
            imovel.setValormaximo(jtfValorMax.getText());
            imovel.setValorminimo(jtfValorMin.getText());
       
            ImovelControle.insereImovel(imovel);
            limparFormulario();
            ArrayList<Imoveis> listaImoveis = ImovelControle.listar();
            Imoveis2Table model = (Imoveis2Table) jTableImoveis.getModel();
            model.setImoveis(listaImoveis);
      
    
       
    }//GEN-LAST:event_jmSalvarActionPerformed

    private boolean validaSeVazio(){
    if (jtfEndereco.getText().isEmpty()||       
        jtfNumero.getText().isEmpty()||
        jtfBairro.getText().isEmpty()||
        jtfCidade.getText().isEmpty()||
        jtfEstado.getText().isEmpty()||
        jtfPais.getText().isEmpty()||
        jtfNome.getText().isEmpty()||
        jtfTel.getText().isEmpty()||
        jtfValorMin.getText().isEmpty()||
        jtfValorMax.getText().isEmpty())
        return false;
    
     return true;
  }  
    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jtfEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoKeyReleased

    private void jtfBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBairroKeyReleased
        // TODO add your handling code here:
        validaString(evt);
    }//GEN-LAST:event_jtfBairroKeyReleased

    private void jtfCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyReleased
        // TODO add your handling code here:
        validaString(evt);
    }//GEN-LAST:event_jtfCidadeKeyReleased

    private void jtfEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEstadoKeyReleased
        // TODO add your handling code here:
        validaString(evt);
    }//GEN-LAST:event_jtfEstadoKeyReleased

    private void jtfPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPaisKeyReleased
        // TODO add your handling code here:
        validaString(evt);
    }//GEN-LAST:event_jtfPaisKeyReleased

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        // TODO add your handling code here:
        validaString(evt);
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroKeyReleased
        // TODO add your handling code here:
        validaNumero(evt);
    }//GEN-LAST:event_jtfNumeroKeyReleased

    private void jtfTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTelKeyReleased
        // TODO add your handling code here:
        validaNumero(evt);
    }//GEN-LAST:event_jtfTelKeyReleased

    private void jtfValorMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorMinKeyReleased
        // TODO add your handling code here:
        validaNumero(evt);
    }//GEN-LAST:event_jtfValorMinKeyReleased

    private void jtfValorMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorMaxKeyReleased
        // TODO add your handling code here:
        validaNumero(evt);
    }//GEN-LAST:event_jtfValorMaxKeyReleased

    private void jmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCancelarActionPerformed
        // TODO add your handling code here:
        limparFormulario();
    }//GEN-LAST:event_jmCancelarActionPerformed

    private void jTableImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableImoveisMouseClicked
        if (evt.getClickCount() >= 2) {
            int linhaSelecionada = jTableImoveis.getSelectedRow();

            if (linhaSelecionada == -1) {
                return;
            }
            else{
            Imoveis2Table model = (Imoveis2Table) jTableImoveis.getModel();
            Imoveis ImovelSelecionado = model.getSelectedImoveis(linhaSelecionada);
            idDoImovelCarregado = ImovelSelecionado.getCodigo();
            jtfNome.setText(ImovelSelecionado.getProprietario());
            jtfEndereco.setText(ImovelSelecionado.getEndereco());
            jtfNumero.setText(ImovelSelecionado.getNumero());
            jtfBairro.setText(ImovelSelecionado.getBairro());
            jtfCidade.setText(ImovelSelecionado.getCidade());
            jtfEstado.setText(ImovelSelecionado.getEstado());
            jtfPais.setText(ImovelSelecionado.getPais());
            jtfTel.setText(ImovelSelecionado.getTelefone());
            jtfValorMin.setText(ImovelSelecionado.getValorminimo());
            jtfValorMax.setText(ImovelSelecionado.getValormaximo());
            }
    }//GEN-LAST:event_jTableImoveisMouseClicked
 }
    private void jmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExcluirActionPerformed
        int linhaSelecionada = jTableImoveis.getSelectedRow();
        if (linhaSelecionada == -1) {
            return;
        }
        Imoveis2Table model = (Imoveis2Table) jTableImoveis.getModel();
        Imoveis imovelSelecionado = model.getSelectedImoveis(linhaSelecionada);
        ImovelControle.removeImovel(imovelSelecionado);
        model.removeImoveis(linhaSelecionada);
    }//GEN-LAST:event_jmExcluirActionPerformed
  //Este é o evento do checkbox hibernate, aqui eu estou determinando se meu controle irá instanciar um jdbc ou um hibernate
    private void jcbHibernateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHibernateActionPerformed
       if(jcbHibernate.isSelected())
           ImovelControle = new ImoveisHibernateDao();
       else
           ImovelControle = new ImoveisJdbcDao();
    }//GEN-LAST:event_jcbHibernateActionPerformed
 
    

    public void limparFormulario() {
        jtfBairro.setText("");
        jtfCidade.setText("");
        jtfEndereco.setText("");
        jtfEstado.setText("");
        jtfTel.setText("");
        jtfNome.setText("");
        jtfNumero.setText("");
        jtfPais.setText("");
        jtfValorMax.setText("");
        jtfValorMin.setText("");
    }

    public void validaNumero(KeyEvent evt) {
        if (evt.getKeyCode() > 57) {
            JTextField campo = (JTextField) evt.getSource();
            campo.setText(removeUltimo(campo.getText()));
        }
    }

    private String removeUltimo(String palavra) {
        int totalDeCaracteres = palavra.length();
        String retorno = palavra.substring(0, totalDeCaracteres - 1);
        return retorno;
    }

    public void validaString(KeyEvent evt) {
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            JTextField campo = (JTextField) evt.getSource();
            campo.setText(removeUltimo(campo.getText()));
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableImoveis;
    private javax.swing.JCheckBox jcbHibernate;
    private javax.swing.JMenu jmAcoes;
    private javax.swing.JMenuItem jmCancelar;
    private javax.swing.JMenuItem jmExcluir;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenuItem jmSalvar;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfPais;
    private javax.swing.JFormattedTextField jtfTel;
    private javax.swing.JTextField jtfValorMax;
    private javax.swing.JTextField jtfValorMin;
    // End of variables declaration//GEN-END:variables


}
