/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imobiliaria.gui;

import imobiliaria.controle.ClientesControle;
import imobiliaria.dao.ClientesHibernateDao;
import imobiliaria.dao.ClientesJDBCDao;
import imobiliaria.modelo.Clientes;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author manuela
 */
public class CadastroCliente extends javax.swing.JFrame {

    private ClientesControle clienteControle;
    private int codigoSelecionado;

    public CadastroCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        Clientes2Table model = new Clientes2Table();
        jTableClientesCadastrados.setModel(model);
        clienteControle = new ClientesJDBCDao();
        // clienteControle = new ClientesHibernateDao();
        ArrayList<Clientes> listaDeClientes = clienteControle.listar();
        model.setClientes(listaDeClientes);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanelDadosDeEndereco = new javax.swing.JPanel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxRenda = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxVenda = new javax.swing.JCheckBox();
        jCheckBoxLocacao = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBoxHibernate = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientesCadastrados = new javax.swing.JTable();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldBuscaCPF = new javax.swing.JTextField();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelDadosDeEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Endereço"));

        jTextFieldEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEstadoFocusLost(evt);
            }
        });

        jLabel6.setText("CEP:");

        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });

        jLabel2.setText("Endereço:");

        jLabel5.setText("Estado:");

        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });

        jLabel3.setText("Bairro:");

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });

        jLabel4.setText("Cidade:");

        jTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCEPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosDeEnderecoLayout = new javax.swing.GroupLayout(jPanelDadosDeEndereco);
        jPanelDadosDeEndereco.setLayout(jPanelDadosDeEnderecoLayout);
        jPanelDadosDeEnderecoLayout.setHorizontalGroup(
            jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCEP)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelDadosDeEnderecoLayout.setVerticalGroup(
            jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de identificação"));

        jLabel1.setText("Nome Completo:");

        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jLabel7.setText("CPF:");

        jTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCPFFocusLost(evt);
            }
        });

        jLabel8.setText("Sexo:");

        buttonGroupSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");

        buttonGroupSexo.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("Feminino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFeminino))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jRadioButtonFeminino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Contato"));

        jLabel9.setText("Telefone:");

        jLabel10.setText("Email:");

        jTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefoneFocusLost(evt);
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jTextFieldTelefone)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Complementares"));

        jLabel11.setText("Renda:");

        jComboBoxRenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Até 1 salário mínimo", "De 2 a 3 salários mínimos", "De 3 a 4 salários mínimos", "De 4 a 5 salários mínimos", "De 5 a 6 salários mínimos", "Sou ricão" }));
        jComboBoxRenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxRendaFocusLost(evt);
            }
        });

        jLabel12.setText("Interesses:");

        jCheckBoxVenda.setText("Venda");

        jCheckBoxLocacao.setText("Locação");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxLocacao))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCheckBoxVenda)
                    .addComponent(jCheckBoxLocacao))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Bem vindo ao cadastro de clientes!");

        jLabel14.setText("Usar hibernate?");

        jCheckBoxHibernate.setText("Sim!");
        jCheckBoxHibernate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHibernateActionPerformed(evt);
            }
        });

        jTableClientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableClientesCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesCadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientesCadastrados);

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Localizar por CPF:");

        jButtonLocalizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxHibernate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDadosDeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLocalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCheckBoxHibernate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDadosDeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jButtonLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       
        
       if(!validaFormulario()){
           JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos ou preenchidos incorretamente!");
           return;
       }
        
        Clientes cliente = new Clientes();

        if (codigoSelecionado != 0) {
            cliente.setCodigo(codigoSelecionado);
            codigoSelecionado = 0;
        }
        cliente.setNome(jTextFieldNome.getText());
        cliente.setCpf(jTextFieldCPF.getText());
        if (jRadioButtonMasculino.isSelected()) {
            cliente.setMasculino(true);
        } else {
            cliente.setMasculino(false);
        }
        cliente.setEndereco(jTextFieldEndereco.getText());
        cliente.setBairro(jTextFieldBairro.getText());
        cliente.setCidade(jTextFieldCidade.getText());
        cliente.setEstado(jTextFieldEstado.getText());
        cliente.setCep(jTextFieldCEP.getText());
        cliente.setTelefone(jTextFieldTelefone.getText());
        cliente.setEmail(jTextFieldEmail.getText());
        cliente.setRenda((String) jComboBoxRenda.getSelectedItem());
        if (jCheckBoxLocacao.isSelected()) {
            cliente.setLocacao(true);
            cliente.setVenda(false);
        } else {
            cliente.setLocacao(false);
            cliente.setVenda(true);
        }

        clienteControle.salvar(cliente);
        resetFormulario();
        ArrayList<Clientes> listaDeClientes = clienteControle.listar();
        Clientes2Table model = (Clientes2Table) jTableClientesCadastrados.getModel();
        model.setClientes(listaDeClientes);


    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jCheckBoxHibernateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHibernateActionPerformed
        if (jCheckBoxHibernate.isSelected()) {
            clienteControle = new ClientesHibernateDao();
        } else {
            clienteControle = new ClientesJDBCDao();
        }
    }//GEN-LAST:event_jCheckBoxHibernateActionPerformed

    private void jTableClientesCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesCadastradosMouseClicked
        if (evt.getClickCount() >= 2) {
            int linhaSelecionada = jTableClientesCadastrados.getSelectedRow();

            if (linhaSelecionada == -1) {
                return;
            }
            Clientes2Table model = (Clientes2Table) jTableClientesCadastrados.getModel();
            Clientes clienteSelecionado = model.getSelectedCliente(linhaSelecionada);
            codigoSelecionado = clienteSelecionado.getCodigo();
            jTextFieldNome.setText(clienteSelecionado.getNome());
            jTextFieldCPF.setText(clienteSelecionado.getCpf());
            if (clienteSelecionado.isMasculino()) {
                jRadioButtonMasculino.setSelected(true);
                jRadioButtonFeminino.setSelected(false);
            } else {
                jRadioButtonMasculino.setSelected(false);
                jRadioButtonFeminino.setSelected(true);
            }
            jTextFieldEndereco.setText(clienteSelecionado.getEndereco());
            jTextFieldBairro.setText(clienteSelecionado.getBairro());
            jTextFieldCidade.setText(clienteSelecionado.getCidade());
            jTextFieldEstado.setText(clienteSelecionado.getEstado());
            jTextFieldCEP.setText(clienteSelecionado.getCep());
            jTextFieldTelefone.setText(clienteSelecionado.getTelefone());
            jTextFieldEmail.setText(clienteSelecionado.getEmail());
            jComboBoxRenda.setSelectedItem(clienteSelecionado.getRenda());
            if (clienteSelecionado.getVenda() == true) {
                jCheckBoxVenda.setSelected(true);
            } else {
                jCheckBoxVenda.setSelected(false);
            }
            if (clienteSelecionado.getLocacao() == true) {
                jCheckBoxLocacao.setSelected(true);
            } else {
                jCheckBoxLocacao.setSelected(false);
            }
        }

    }//GEN-LAST:event_jTableClientesCadastradosMouseClicked

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        if (jTextFieldNome.getText().isEmpty()) {
            jTextFieldNome.setBackground(Color.RED);
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCPFFocusLost
        if (jTextFieldCPF.getText().isEmpty()) {
            jTextFieldCPF.setBackground(Color.RED);
        } else {
            jTextFieldCPF.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCPFFocusLost

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        if (jTextFieldEndereco.getText().isEmpty()) {
            jTextFieldEndereco.setBackground(Color.RED);
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        if (jTextFieldBairro.getText().isEmpty()) {
            jTextFieldBairro.setBackground(Color.RED);
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        if (jTextFieldCidade.getText().isEmpty()) {
            jTextFieldCidade.setBackground(Color.RED);
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jTextFieldEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEstadoFocusLost
        if (jTextFieldEstado.getText().isEmpty()) {
            jTextFieldEstado.setBackground(Color.RED);
        } else {
            jTextFieldEstado.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEstadoFocusLost

    private void jTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCEPFocusLost
        if (jTextFieldCEP.getText().isEmpty()) {
            jTextFieldCEP.setBackground(Color.RED);
        } else {
            jTextFieldCEP.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCEPFocusLost

    private void jTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneFocusLost
        if (jTextFieldTelefone.getText().isEmpty()) {
            jTextFieldTelefone.setBackground(Color.RED);
        } else {
            jTextFieldTelefone.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldTelefoneFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (jTextFieldEmail.getText().isEmpty() || !jTextFieldEmail.getText().matches("[a-zA-Z0-9]+[a-zA-Z0-9_.-]+@{1}[a-zA-Z0-9_.-]*\\.+[a-z]{2,4}")) {
            jTextFieldEmail.setBackground(Color.RED);
        } else {
            jTextFieldEmail.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jComboBoxRendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxRendaFocusLost
        if (jComboBoxRenda.getSelectedIndex() == 0) {
            jComboBoxRenda.setBackground(Color.RED);
        } else {
            jComboBoxRenda.setBackground(null);
    }//GEN-LAST:event_jComboBoxRendaFocusLost
    }
    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        int linhaSelecionada = jTableClientesCadastrados.getSelectedRow();
        if (linhaSelecionada == -1) {
            return;
        }
        Clientes2Table model = (Clientes2Table) jTableClientesCadastrados.getModel();
        Clientes clienteSelecionado = model.getSelectedCliente(linhaSelecionada);
        clienteControle.excluir(clienteSelecionado);
        model.removeCliente(linhaSelecionada);
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        ArrayList<Clientes> clientesEncontrados = clienteControle.pesquisarClientesPorCPF(jTextFieldBuscaCPF.getText());
        if (clientesEncontrados == null) {
            JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado com o cpf especificado!");
        } else {
            
            Clientes2Table model = (Clientes2Table) jTableClientesCadastrados.getModel();
            model.setClientes(clientesEncontrados);
            jTextFieldBuscaCPF.setText("");
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        Clientes2Table model = (Clientes2Table) jTableClientesCadastrados.getModel();
        ArrayList<Clientes> listaDeClientes = clienteControle.listar();
        model.setClientes(listaDeClientes);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void resetFormulario() {

        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jRadioButtonFeminino.setSelected(false);
        jRadioButtonMasculino.setSelected(false);
        jTextFieldEndereco.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCEP.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jComboBoxRenda.setSelectedIndex(0);
        jCheckBoxLocacao.setSelected(false);
        jCheckBoxVenda.setSelected(false);
    }

    private boolean validaFormulario() {
        boolean formularioValido = true;

        if (jTextFieldNome.getText().isEmpty()) {
            jTextFieldNome.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
        if (jTextFieldCPF.getText().isEmpty()) {
            jTextFieldCPF.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCPF.setBackground(Color.white);
        }
        if (jTextFieldEndereco.getText().isEmpty()) {
            jTextFieldEndereco.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
        if (jTextFieldBairro.getText().isEmpty()) {
            jTextFieldBairro.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
        if (jTextFieldCidade.getText().isEmpty()) {
            jTextFieldCidade.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
        if (jTextFieldEstado.getText().isEmpty()) {
            jTextFieldEstado.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEstado.setBackground(Color.white);

        }
        if (jTextFieldCEP.getText().isEmpty()) {
            jTextFieldCEP.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCEP.setBackground(Color.white);
        }

        if (jTextFieldTelefone.getText().isEmpty()) {
            jTextFieldTelefone.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldTelefone.setBackground(Color.white);
        }

        if (jTextFieldEmail.getText().isEmpty() || !jTextFieldEmail.getText().matches("[a-zA-Z0-9]+[a-zA-Z0-9_.-]+@{1}[a-zA-Z0-9_.-]*\\.+[a-z]{2,4}")) {
            jTextFieldEmail.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEmail.setBackground(Color.white);
        }
        if (jComboBoxRenda.getSelectedIndex() == 0) {
            jComboBoxRenda.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jComboBoxRenda.setBackground(null);
        }

        return  formularioValido;
    }

    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
//
   //     java.awt.EventQueue.invokeLater(new Runnable() {
       //     @Override
        //    public void run() {
        //        new CadastroCliente().setVisible(true);
        //    }
        //});
   // }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JCheckBox jCheckBoxHibernate;
    private javax.swing.JCheckBox jCheckBoxLocacao;
    private javax.swing.JCheckBox jCheckBoxVenda;
    private javax.swing.JComboBox jComboBoxRenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDadosDeEndereco;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientesCadastrados;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBuscaCPF;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
