/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imobiliaria.gui;

import imobiliaria.controle.FuncionariosControle;
import imobiliaria.dao.FuncionariosHibernate;

import imobiliaria.modelo.Funcionarios;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author André
 */
public class CadastroFuncionarios extends javax.swing.JFrame {
    
     private FuncionariosControle funcionarioControle;
    private int codigoSelecionado;

    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        Funcionarios2Table model = new Funcionarios2Table();
        jTableFuncionariosCadastrados.setModel(model);
        funcionarioControle = new FuncionariosHibernate();
        
        ArrayList<Funcionarios> listaDeClientes = funcionarioControle.listar();
        model.setFuncionarios(listaDeClientes);
    }
    
    private boolean validaFormulario() {
        boolean formularioValido = true;

        if (jTextFieldNome.getText().isEmpty()) {
            jTextFieldNome.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
        if (jTextFieldCPF.getText().isEmpty()) {
            jTextFieldCPF.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCPF.setBackground(Color.white);
        }
        if (jTextFieldEndereco.getText().isEmpty()) {
            jTextFieldEndereco.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
        if (jTextFieldBairro.getText().isEmpty()) {
            jTextFieldBairro.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
        if (jTextFieldCidade.getText().isEmpty()) {
            jTextFieldCidade.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
        if (jTextFieldEstado.getText().isEmpty()) {
            jTextFieldEstado.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEstado.setBackground(Color.white);

        }
        if (jTextFieldCEP.getText().isEmpty()) {
            jTextFieldCEP.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldCEP.setBackground(Color.white);
        }

        if (jTextFieldTelefone.getText().isEmpty()) {
            jTextFieldTelefone.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldTelefone.setBackground(Color.white);
        }

        if (jTextFieldEmail.getText().isEmpty() || !jTextFieldEmail.getText().matches("[a-zA-Z0-9]+[a-zA-Z0-9_.-]+@{1}[a-zA-Z0-9_.-]*\\.+[a-z]{2,4}")) {
            jTextFieldEmail.setBackground(Color.RED);
            formularioValido = false;
        } else {
            jTextFieldEmail.setBackground(Color.white);
        }
        
        return  formularioValido;
    }
    
    private void resetFormulario() {

        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jTFCtps.setText("");
        jRadioButtonFeminino.setSelected(false);
        jRadioButtonMasculino.setSelected(false);
        jTextFieldEndereco.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCEP.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTfSalario.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTFCtps = new javax.swing.JTextField();
        jPanelDadosDeEndereco = new javax.swing.JPanel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTfSalario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfCargo = new javax.swing.JTextField();
        jTextFieldBuscaCPF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionariosCadastrados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jrbCargo = new javax.swing.JRadioButton();
        jrbNome = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de identificação"));

        jLabel1.setText("Nome Completo:");

        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jLabel7.setText("CPF:");

        jTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCPFFocusLost(evt);
            }
        });

        jLabel8.setText("Sexo:");

        jRadioButtonMasculino.setText("Masculino");

        jRadioButtonFeminino.setText("Feminino");

        jLabel12.setText("CTPS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFeminino)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCtps)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jRadioButtonFeminino)
                    .addComponent(jLabel12)
                    .addComponent(jTFCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDadosDeEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Endereço"));

        jTextFieldEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEstadoFocusLost(evt);
            }
        });

        jLabel6.setText("CEP:");

        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });

        jLabel2.setText("Endereço:");

        jLabel5.setText("Estado:");

        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });

        jLabel3.setText("Bairro:");

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });

        jLabel4.setText("Cidade:");

        jTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCEPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosDeEnderecoLayout = new javax.swing.GroupLayout(jPanelDadosDeEndereco);
        jPanelDadosDeEndereco.setLayout(jPanelDadosDeEnderecoLayout);
        jPanelDadosDeEnderecoLayout.setHorizontalGroup(
            jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCEP)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelDadosDeEnderecoLayout.setVerticalGroup(
            jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDeEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosDeEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Contato"));

        jLabel9.setText("Telefone:");

        jLabel10.setText("Email:");

        jTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefoneFocusLost(evt);
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jTextFieldTelefone)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Complementares"));

        jLabel11.setText("Renda:");

        jLabel14.setText("Cargo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCargo)))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Localizar:");

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonLocalizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jButtonRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTableFuncionariosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFuncionariosCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosCadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionariosCadastrados);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cadastro de Funcionários:");

        buttonGroup1.add(jrbCargo);
        jrbCargo.setText("Cargo");
        jrbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCargoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbNome);
        jrbNome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDadosDeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbNome)
                                    .addComponent(jrbCargo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLocalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDadosDeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        if (jTextFieldNome.getText().isEmpty()) {
            jTextFieldNome.setBackground(Color.RED);
        } else {
            jTextFieldNome.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCPFFocusLost
        if (jTextFieldCPF.getText().isEmpty()) {
            jTextFieldCPF.setBackground(Color.RED);
        } else {
            jTextFieldCPF.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCPFFocusLost

    private void jTextFieldEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEstadoFocusLost
        if (jTextFieldEstado.getText().isEmpty()) {
            jTextFieldEstado.setBackground(Color.RED);
        } else {
            jTextFieldEstado.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEstadoFocusLost

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        if (jTextFieldCidade.getText().isEmpty()) {
            jTextFieldCidade.setBackground(Color.RED);
        } else {
            jTextFieldCidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        if (jTextFieldEndereco.getText().isEmpty()) {
            jTextFieldEndereco.setBackground(Color.RED);
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        if (jTextFieldBairro.getText().isEmpty()) {
            jTextFieldBairro.setBackground(Color.RED);
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCEPFocusLost
        if (jTextFieldCEP.getText().isEmpty()) {
            jTextFieldCEP.setBackground(Color.RED);
        } else {
            jTextFieldCEP.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCEPFocusLost

    private void jTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneFocusLost
        if (jTextFieldTelefone.getText().isEmpty()) {
            jTextFieldTelefone.setBackground(Color.RED);
        } else {
            jTextFieldTelefone.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldTelefoneFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (jTextFieldEmail.getText().isEmpty() || !jTextFieldEmail.getText().matches("[a-zA-Z0-9]+[a-zA-Z0-9_.-]+@{1}[a-zA-Z0-9_.-]*\\.+[a-z]{2,4}")) {
            jTextFieldEmail.setBackground(Color.RED);
        } else {
            jTextFieldEmail.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
        ArrayList<Funcionarios> listaDeFuncionarios = funcionarioControle.listar();
        model.setFuncionarios(listaDeFuncionarios);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        if(jrbCargo.isSelected()){
        ArrayList<Funcionarios> funcionariosEncontrados = funcionarioControle.pesquisarFuncionariosPorCargo(jTextFieldBuscaCPF.getText());
        if (funcionariosEncontrados == null) {
            JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado com o Cargo especificado!");
        } else {
            
            Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
            model.setFuncionarios(funcionariosEncontrados);
            jTextFieldBuscaCPF.setText("");
        }
        }
        if(jrbNome.isSelected()){
        ArrayList<Funcionarios> funcionariosEncontrados = funcionarioControle.pesquisarFuncionariosPorNome(jTextFieldBuscaCPF.getText());
        if (funcionariosEncontrados == null) {
            JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado com o Nome especificado!");
        } else {
            
            Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
            model.setFuncionarios(funcionariosEncontrados);
            jTextFieldBuscaCPF.setText("");
        }    
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        int linhaSelecionada = jTableFuncionariosCadastrados.getSelectedRow();
        if (linhaSelecionada == -1) {
            return;
        }
        Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
        Funcionarios clienteSelecionado = model.getSelectedFuncionario(linhaSelecionada);
        funcionarioControle.excluir(clienteSelecionado);
        model.removeFuncionario(linhaSelecionada);
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        funcionarioControle = new FuncionariosHibernate();
        if(!validaFormulario()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos ou preenchidos incorretamente!");
            return;
        }

        Funcionarios funcionario = new Funcionarios();

        if (codigoSelecionado != 0) {
            funcionario.setCodigo(codigoSelecionado);
            codigoSelecionado = 0;
        }
        funcionario.setNome(jTextFieldNome.getText());
        funcionario.setCpf(jTextFieldCPF.getText());
        funcionario.setCtps(jTFCtps.getText());
        if (jRadioButtonMasculino.isSelected()) {
            funcionario.setMasculino(true);
        } else {
            funcionario.setMasculino(false);
        }
        funcionario.setEndereco(jTextFieldEndereco.getText());
        funcionario.setBairro(jTextFieldBairro.getText());
        funcionario.setCidade(jTextFieldCidade.getText());
        funcionario.setEstado(jTextFieldEstado.getText());
        funcionario.setCep(jTextFieldCEP.getText());
        funcionario.setTelefone(jTextFieldTelefone.getText());
        funcionario.setEmail(jTextFieldEmail.getText());
        funcionario.setSalario(jTfSalario.getText());
        funcionario.setCargo(jtfCargo.getText());
        

        funcionarioControle.salvar(funcionario);
        resetFormulario();
        ArrayList<Funcionarios> listaDeFuncionarios = funcionarioControle.listar();
        Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
        model.setFuncionarios(listaDeFuncionarios);

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTableFuncionariosCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosCadastradosMouseClicked
        if (evt.getClickCount() >= 2) {
            int linhaSelecionada = jTableFuncionariosCadastrados.getSelectedRow();

            if (linhaSelecionada == -1) {
                return;
            }
            Funcionarios2Table model = (Funcionarios2Table) jTableFuncionariosCadastrados.getModel();
            Funcionarios funcionarioSelecionado = model.getSelectedFuncionario(linhaSelecionada);
            codigoSelecionado = funcionarioSelecionado.getCodigo();
            jTextFieldNome.setText(funcionarioSelecionado.getNome());
            jTextFieldCPF.setText(funcionarioSelecionado.getCpf());
            jTFCtps.setText(funcionarioSelecionado.getCtps());
            if (funcionarioSelecionado.getMasculino()==true) {
                jRadioButtonMasculino.setSelected(true);
                jRadioButtonFeminino.setSelected(false);
            } else {
                jRadioButtonMasculino.setSelected(false);
                jRadioButtonFeminino.setSelected(true);
            }
            jTextFieldEndereco.setText(funcionarioSelecionado.getEndereco());
            jTextFieldBairro.setText(funcionarioSelecionado.getBairro());
            jTextFieldCidade.setText(funcionarioSelecionado.getCidade());
            jTextFieldEstado.setText(funcionarioSelecionado.getEstado());
            jTextFieldCEP.setText(funcionarioSelecionado.getCep());
            jTextFieldTelefone.setText(funcionarioSelecionado.getTelefone());
            jTextFieldEmail.setText(funcionarioSelecionado.getEmail());
            jTfSalario.setText(funcionarioSelecionado.getSalario());
           
        }
    }//GEN-LAST:event_jTableFuncionariosCadastradosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDadosDeEndereco;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCtps;
    private javax.swing.JTable jTableFuncionariosCadastrados;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBuscaCPF;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTfSalario;
    private javax.swing.JRadioButton jrbCargo;
    private javax.swing.JRadioButton jrbNome;
    private javax.swing.JTextField jtfCargo;
    // End of variables declaration//GEN-END:variables
}
