package imobiliaria.modelo;
// Generated 21/06/2013 16:28:22 by Hibernate Tools 3.2.1.GA


import imobiliaria.gui.Clientes2Table;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="CLIENTES"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Clientes  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String cpf;
     private boolean masculino;
     private String endereco;
     private String bairro;
     private String cidade;
     private String estado;
     private String cep;
     private String telefone;
     private String email;
     private String renda;
     private Boolean venda;
     private Boolean locacao;

    public Clientes() {
    }

	
    public Clientes(int codigo, String nome, String cpf, boolean masculino, String endereco, String bairro, String cidade, String estado, String cep, String telefone, String email, String renda) {
        this.codigo = codigo;
        this.nome = nome;
        this.cpf = cpf;
        this.masculino = masculino;
        this.endereco = endereco;
        this.bairro = bairro;
        this.cidade = cidade;
        this.estado = estado;
        this.cep = cep;
        this.telefone = telefone;
        this.email = email;
        this.renda = renda;
    }
    public Clientes(int codigo, String nome, String cpf, boolean masculino, String endereco, String bairro, String cidade, String estado, String cep, String telefone, String email, String renda, Boolean venda, Boolean locacao) {
       this.codigo = codigo;
       this.nome = nome;
       this.cpf = cpf;
       this.masculino = masculino;
       this.endereco = endereco;
       this.bairro = bairro;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.telefone = telefone;
       this.email = email;
       this.renda = renda;
       this.venda = venda;
       this.locacao = locacao;
    }
   
     @Id 
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="CODIGO", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="CPF", nullable=false)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
    @Column(name="MASCULINO", nullable=false)
    public boolean isMasculino() {
        return this.masculino;
    }
    
    public void setMasculino(boolean masculino) {
        this.masculino = masculino;
    }
    
    @Column(name="ENDERECO", nullable=false, length=100)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    
    @Column(name="BAIRRO", nullable=false, length=50)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    
    @Column(name="CIDADE", nullable=false, length=20)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    
    @Column(name="ESTADO", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="CEP", nullable=false, length=20)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    
    @Column(name="TELEFONE", nullable=false, length=14)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="RENDA", nullable=false, length=50)
    public String getRenda() {
        return this.renda;
    }
    
    public void setRenda(String renda) {
        this.renda = renda;
    }
    
    @Column(name="VENDA")
    public Boolean getVenda() {
        return this.venda;
    }
    
    public void setVenda(Boolean venda) {
        this.venda = venda;
    }
    
    @Column(name="LOCACAO")
    public Boolean getLocacao() {
        return this.locacao;
    }
    
    public void setLocacao(Boolean locacao) {
        this.locacao = locacao;
    }
 @Override
    public String toString(){
        return String.valueOf(this.codigo);
    }
    
     public String[] toArray() {
        String[] arrayClientes = new String[6];
        arrayClientes[Clientes2Table.INDICE_CODIGO] = String.valueOf(this.getCodigo());
        arrayClientes[Clientes2Table.INDICE_NOME] = this.getNome();
        arrayClientes[Clientes2Table.INDICE_CPF] = this.getCpf();
        
        return arrayClientes;
    }



}


